name: ppok
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h578d9bd_1
  - cffi=1.15.0=py38hd667e15_1
  - chardet=4.0.0=py38h578d9bd_2
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - decorator=5.1.1=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.2.0=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_4
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.0=pyh6c4a22f_1
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.38.1=py38hdd6454d_0
  - huggingface_hub=0.2.1=pyhd3eb1b0_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py38h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipdb=0.13.9=pyhd8ed1ab_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - jedi=0.18.1=py38h06a4308_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h780b84a_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=5.1.0=py38h497a2fe_1
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=py38hd09550d_3
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.1.3=py38he6710b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.17.2=py38h709712a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-lightning=1.5.10=pyhd8ed1ab_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h7f8727e_1
  - readline=8.1.2=h7f8727e_1
  - regex=2021.11.2=py38h7f8727e_0
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.0=hc218d9a_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.0=py38h2b97feb_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - tokenizers=0.10.3=py38hb317417_1
  - torchaudio=0.8.1=py38
  - torchmetrics=0.7.2=pyhd8ed1ab_0
  - torchvision=0.9.1=py38_cu102
  - tqdm=4.63.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - transformers=4.16.2=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.3=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h497a2fe_2
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - sentencepiece==0.1.96
prefix: /home/ximinglu/anaconda3/envs/ppok
